"""add withdrawn status

Revision ID: 237b488a1c1d
Revises: b2835f6b62bd
Create Date: 2026-08-05 18:11:23.506029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237b488a1c1d'
down_revision: Union[str, Sequence[str], None] = 'b2835f6b62bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written rather than autogenerated: Alembic's default comparator doesn't
    # reliably detect new members added to an existing Postgres native enum type.
    op.execute("ALTER TYPE application_status ADD VALUE 'withdrawn'")


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres has no DROP VALUE for enums — removing one cleanly requires recreating
    # the whole type. Not worth the complexity for a solo-user app; left as a no-op.
    pass
