"""add tailoring quota fields to users

Revision ID: 775286549a80
Revises: 237b488a1c1d
Create Date: 2026-08-13 11:33:56.487651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775286549a80'
down_revision: Union[str, Sequence[str], None] = '237b488a1c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('unlimited_tailoring', sa.Boolean(), server_default=sa.text('false'), nullable=False)
    )
    op.add_column('users', sa.Column('tailor_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('tailor_count_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tailor_count_date')
    op.drop_column('users', 'tailor_count')
    op.drop_column('users', 'unlimited_tailoring')
    # ### end Alembic commands ###
