"""add ever_interviewed to applications

Revision ID: a5ad8b07e160
Revises: a0649c7b4666
Create Date: 2026-08-16 22:44:09.324139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ad8b07e160'
down_revision: Union[str, Sequence[str], None] = 'a0649c7b4666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('ever_interviewed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Data backfill (not autogenerated): applications currently sitting at screening/interview/
    # offer are, by definition, applications that have reached interview stage — flag them
    # retroactively. Ones already rejected/withdrawn *after* having interviewed can't be
    # recovered (that history was never tracked), which is an accepted, unavoidable gap.
    op.execute(
        "UPDATE applications SET ever_interviewed = true "
        "WHERE status IN ('screening', 'interview', 'offer')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'ever_interviewed')
    # ### end Alembic commands ###
