"""add waiting status

Revision ID: f3c1a9d2e4b7
Revises: a5ad8b07e160
Create Date: 2026-08-17 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c1a9d2e4b7'
down_revision: Union[str, Sequence[str], None] = 'a5ad8b07e160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written rather than autogenerated: Alembic's default comparator doesn't
    # reliably detect new members added to an existing Postgres native enum type.
    op.execute("ALTER TYPE application_status ADD VALUE 'waiting'")


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres has no DROP VALUE for enums — removing one cleanly requires recreating
    # the whole type. Not worth the complexity for a solo-user app; left as a no-op.
    pass
